annotations:
  category: Infrastructure

apiVersion: v2
name: cells
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0-beta.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v4"

home: https://pydio.com
icon: https://pydio.com/sites/all/themes/pydio_theme/images/logoPydioWhite.png

sources:
  - https://github.com/pydio/cells

maintainers:
  - name: Pydio
    url: https://github.com/pydio/cells/tools/kubernetes

keywords:
  - pydio
  - cells
  - storage
  - object-storage
  - s3
  - cluster

dependencies:
  - name: common
    version: 2.x.x
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: mariadb
    condition: mariadb.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "20.5.5"
  # Mariadb galera is legacy as it is included in mariadb
  - name: mariadb-galera
    condition: mariadb-galera.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "x.x.x"
  - name: redis
    condition: redis.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "21.x.x"
  - name: nats
    condition: nats.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "9.0.17"
  - name: mongodb
    condition: mongodb.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "16.5.7"
  - name: etcd
    condition: etcd.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "11.3.x"
  - name: minio
    condition: minio.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "16.0.10"
  - name: ingress-nginx
    condition: ingress.enabled
    repository: https://kubernetes.github.io/ingress-nginx
    version: x.x.x
  - name: vault  
    condition: vault.enabled
    repository: https://helm.releases.hashicorp.com
    version: x.x.x
  - name: cert-manager
    condition: cert-manager.enabled
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: x.x.x
