// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: sync.proto

package sync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/pydio/cells/v4/common/proto/jobs"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SyncEndpoint service

func NewSyncEndpointEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SyncEndpoint service

type SyncEndpointService interface {
	TriggerResync(ctx context.Context, in *ResyncRequest, opts ...client.CallOption) (*ResyncResponse, error)
}

type syncEndpointService struct {
	c    client.Client
	name string
}

func NewSyncEndpointService(name string, c client.Client) SyncEndpointService {
	return &syncEndpointService{
		c:    c,
		name: name,
	}
}

func (c *syncEndpointService) TriggerResync(ctx context.Context, in *ResyncRequest, opts ...client.CallOption) (*ResyncResponse, error) {
	req := c.c.NewRequest(c.name, "SyncEndpoint.TriggerResync", in)
	out := new(ResyncResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SyncEndpoint service

type SyncEndpointHandler interface {
	TriggerResync(context.Context, *ResyncRequest, *ResyncResponse) error
}

func RegisterSyncEndpointHandler(s server.Server, hdlr SyncEndpointHandler, opts ...server.HandlerOption) error {
	type syncEndpoint interface {
		TriggerResync(ctx context.Context, in *ResyncRequest, out *ResyncResponse) error
	}
	type SyncEndpoint struct {
		syncEndpoint
	}
	h := &syncEndpointHandler{hdlr}
	return s.Handle(s.NewHandler(&SyncEndpoint{h}, opts...))
}

type syncEndpointHandler struct {
	SyncEndpointHandler
}

func (h *syncEndpointHandler) TriggerResync(ctx context.Context, in *ResyncRequest, out *ResyncResponse) error {
	return h.SyncEndpointHandler.TriggerResync(ctx, in, out)
}
