// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rest.proto

package rest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/pydio/cells/v4/common/proto/activity"
import _ "github.com/pydio/cells/v4/common/proto/ctl"
import _ "github.com/pydio/cells/v4/common/proto/encryption"
import _ "github.com/pydio/cells/v4/common/proto/idm"
import _ "github.com/pydio/cells/v4/common/proto/install"
import _ "github.com/pydio/cells/v4/common/proto/jobs"
import _ "github.com/pydio/cells/v4/common/proto/log"
import _ "github.com/pydio/cells/v4/common/proto/mailer"
import _ "github.com/pydio/cells/v4/common/proto/object"
import _ "github.com/pydio/cells/v4/common/proto/tree"
import _ "github.com/pydio/cells/v4/common/proto/update"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
