// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Tester service

func NewTesterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Tester service

type TesterService interface {
	Run(ctx context.Context, in *RunTestsRequest, opts ...client.CallOption) (*RunTestsResponse, error)
}

type testerService struct {
	c    client.Client
	name string
}

func NewTesterService(name string, c client.Client) TesterService {
	return &testerService{
		c:    c,
		name: name,
	}
}

func (c *testerService) Run(ctx context.Context, in *RunTestsRequest, opts ...client.CallOption) (*RunTestsResponse, error) {
	req := c.c.NewRequest(c.name, "Tester.Run", in)
	out := new(RunTestsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tester service

type TesterHandler interface {
	Run(context.Context, *RunTestsRequest, *RunTestsResponse) error
}

func RegisterTesterHandler(s server.Server, hdlr TesterHandler, opts ...server.HandlerOption) error {
	type tester interface {
		Run(ctx context.Context, in *RunTestsRequest, out *RunTestsResponse) error
	}
	type Tester struct {
		tester
	}
	h := &testerHandler{hdlr}
	return s.Handle(s.NewHandler(&Tester{h}, opts...))
}

type testerHandler struct {
	TesterHandler
}

func (h *testerHandler) Run(ctx context.Context, in *RunTestsRequest, out *RunTestsResponse) error {
	return h.TesterHandler.Run(ctx, in, out)
}
