// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Starter service

func NewStarterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Starter service

type StarterService interface {
	Start(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*emptypb.Empty, error)
}

type starterService struct {
	c    client.Client
	name string
}

func NewStarterService(name string, c client.Client) StarterService {
	return &starterService{
		c:    c,
		name: name,
	}
}

func (c *starterService) Start(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "Starter.Start", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Starter service

type StarterHandler interface {
	Start(context.Context, *emptypb.Empty, *emptypb.Empty) error
}

func RegisterStarterHandler(s server.Server, hdlr StarterHandler, opts ...server.HandlerOption) error {
	type starter interface {
		Start(ctx context.Context, in *emptypb.Empty, out *emptypb.Empty) error
	}
	type Starter struct {
		starter
	}
	h := &starterHandler{hdlr}
	return s.Handle(s.NewHandler(&Starter{h}, opts...))
}

type starterHandler struct {
	StarterHandler
}

func (h *starterHandler) Start(ctx context.Context, in *emptypb.Empty, out *emptypb.Empty) error {
	return h.StarterHandler.Start(ctx, in, out)
}

// Api Endpoints for Service service

func NewServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Service service

type Service interface {
	Status(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*StatusResponse, error)
}

type service struct {
	c    client.Client
	name string
}

func NewService(name string, c client.Client) Service {
	return &service{
		c:    c,
		name: name,
	}
}

func (c *service) Status(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.name, "Service.Status", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	Status(context.Context, *emptypb.Empty, *StatusResponse) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) error {
	type service interface {
		Status(ctx context.Context, in *emptypb.Empty, out *StatusResponse) error
	}
	type Service struct {
		service
	}
	h := &serviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Service{h}, opts...))
}

type serviceHandler struct {
	ServiceHandler
}

func (h *serviceHandler) Status(ctx context.Context, in *emptypb.Empty, out *StatusResponse) error {
	return h.ServiceHandler.Status(ctx, in, out)
}

// Api Endpoints for Archiver service

func NewArchiverEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Archiver service

type ArchiverService interface {
	Archive(ctx context.Context, in *Query, opts ...client.CallOption) (*StatusResponse, error)
}

type archiverService struct {
	c    client.Client
	name string
}

func NewArchiverService(name string, c client.Client) ArchiverService {
	return &archiverService{
		c:    c,
		name: name,
	}
}

func (c *archiverService) Archive(ctx context.Context, in *Query, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.name, "Archiver.Archive", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Archiver service

type ArchiverHandler interface {
	Archive(context.Context, *Query, *StatusResponse) error
}

func RegisterArchiverHandler(s server.Server, hdlr ArchiverHandler, opts ...server.HandlerOption) error {
	type archiver interface {
		Archive(ctx context.Context, in *Query, out *StatusResponse) error
	}
	type Archiver struct {
		archiver
	}
	h := &archiverHandler{hdlr}
	return s.Handle(s.NewHandler(&Archiver{h}, opts...))
}

type archiverHandler struct {
	ArchiverHandler
}

func (h *archiverHandler) Archive(ctx context.Context, in *Query, out *StatusResponse) error {
	return h.ArchiverHandler.Archive(ctx, in, out)
}
