#listeners:
#  bufconn:
#    type: bufconn
#    bufsize: 1048576
#connections:
#  grpc:
#    type: grpc
#    uri: passthrough://bufnet
#    listener: bufconn
#    services:
#      - filter: "{{ .Name }} ~= .*"
#servers:
#  grpc:
#    type: grpc
#    listener: bufconn
#    services:
#      - filter: "{{ .Name }} ~= .*"


listeners:
  grpc:
    type: grpc
    bind: 0.0.0.0
    port: 8030
  http:
    type: http
    bind: 0.0.0.0
    port: 8080
connections:
  grpc:
    type: grpc
    uri: xds://default.cells.com/cells
    services:
      - filter: "{{ .Name }} ~= .*"
servers:
  grpc:
    type: grpc
    listener: grpc
    services:
      - filter: "{{ .Name }} ~= .*"
  http:
    type: http
    listener: http

processes:
  child1:
    listeners:
      type: http
      bind: 0.0.0.0
      port: 0
    servers:
      http:
        type: http
        listener: http
        services:
          - filter: "{{ .Name }} ~= .*"