services:
  cells:
    image: local
    restart: unless-stopped
    ports: ["8080:8080"]
    environment:
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
    volumes: 
      - cellsdir:/var/cells

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe!
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: ChangeMe!
    volumes:
      - mysqldir:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

volumes:
  cellsdir: {}
  mysqldir: {}
